### ISSUE TITLE
json only house spawn

### ISSUE THREAD

**Issue by ApoWillow** [LunarLuned/Peculia#1]
peculia:json_only_house is a structure which spawns in certain biomes like forest, plains and deserts and etc, it spawns very frequently, so much so that you can find 3 of them in the same area

it seems that this structure isn't supposed to be an actual structure that spawns in the mod

**Comment by LunarLuned** [comment]
Hi!
I  dont know how that slipped through the cracks with whatever release you had gotten (are you using the unfinished snapshot on the discord? that may do it!) But you are absolutely correct. I was using a tutorial file as reference for how structure files work, to understand it better and it may have persisted through one of the snapshot releases. 

Just to make sure is this version from the discord server or from the curseforge page? Thank you!

**Comment by ApoWillow** [comment]
(No I was using the latest version on the curseforge), I understand it's reference, it's alright, we all make mistakes

**Comment by LunarLuned** [comment]
I see. Ill put a fix out on CurseForge later today, but for the meantime-- the discord server does have a snapshot of the new Peculia version, and that bug is fixed there--if you still want to play the mod without those pesky houses
