### ISSUE TITLE
peculia:json_only_house structure generating everywhere.

### ISSUE THREAD

**Issue by itsbanditodorito** [LunarLuned/Peculia#3]
Hi! For whatever reason, recently whenever I would create a world a house would generate frequently. As far as I know, this has not happened on previous versions of peculia. After going into an NBT viewer I found each chunk that had one of these structures generated and it pointed it to being a result of peculia.

**Comment by itsbanditodorito** [comment]
Just checked closed issues after sending this one, it looks like you guys are already aware! So I'll just close this one.

**Comment by LunarLuned** [comment]
Hi!! So sorry for that, I just released a version 1.6.1 that fixes that bug. Thanks for mentioning it! <3

**Comment by itsbanditodorito** [comment]
aaa its nw! this kinda stuff happens to the best of us!! thanks for the speedy fix :p
