### ISSUE TITLE
Compat error with Moonlight Lib

### ISSUE THREAD

**Issue by Sunconure11** [LunarLuned/Peculia#4]
https://gist.github.com/Sunconure11/b4a2289f5cf02f54274832051d4dade1

**Comment by LunarLuned** [comment]
Hi! Okay, so I am not sure why Moonlight Lib affects Peculia but I am confident that if you disable the Milk Bucket rework in the config (preferably with ModMenu) you should stop facing that bug. Will keep you updated!

**Comment by Sunconure11** [comment]
Unfortunately, I can't disable it, as Peculia didn't get loaded enough to gen a config.

**Comment by LunarLuned** [comment]
Right, i'll see what I can do. For now, when I can get home, i can build an alternative version with said option being disabled by default--but this bug is in more of the hands of Moonlight Lib, as theres not much I can do at first glance about it.

**Comment by Sunconure11** [comment]
Computer is also bricked ATM

**Comment by Sunconure11** [comment]
@MehVahdJukaar

You might want to look here.

**Comment by MehVahdJukaar** [comment]
I don't think it's related to my things at all. Only reason it shows up on the stack trace is because my clas happened to be the first one that loaded the class with the faulty mixin in

**Comment by Sunconure11** [comment]
@LunarLuned Currently having internet issues, but these mods also take use of that mixin:

Create, Pehkui, Porting Lib, and Lithium all seem to use the same mixins that are being blamed.

**Comment by LunarLuned** [comment]
Hey all! Sorry, wasn't really a available when this thread revived itself.

I had a mixin for the milk bucket (that had a config, disabled by default iirc) that had changed milk from removing all status effects to removing a bit of the duration of the effects given, as I made an 'elixir' item group, with each one removing groups of negative effects. 

While I still like this idea, if I cant find a way to fix the incompatibility (with the dumbest of reasons???) ill just remove the mixin. Thanks!

**Comment by Sunconure11** [comment]
Maybe move these changes to a new item entirely, as opposed to milk?

**Comment by Sunconure11** [comment]
Sorry if I'm bugging you, but maybe it is time to try and just pull the mixin?

**Comment by LunarLuned** [comment]
You're not bugging me! ive just been physically incapable of doing it at this moment. I get home later today however so I can do it then

**Comment by Sunconure11** [comment]
Did something happen on the way? I'm hesitant to make more posts, but I'm curious as to if there is any progress yet.

**Comment by LunarLuned** [comment]
Sorry bout that, expect it on the Curseforge & Modrinth page in about the next hour or so

**Comment by LunarLuned** [comment]
Alright, Modrinth already has the fix up (because modrinth actually uploads things), so here's their link

**Comment by LunarLuned** [comment]
Alright, Modrinth already has the update on it because it uploads faster there, and it should be on curseforge soon. Heres the link for Modrinth

https://modrinth.com/mod/peculia/version/0.1.7-beta-1.19
Thanks again!
